nelmio_api_doc:
  documentation:
    info:
      title: "API Documentation"
      description: "Dokumentacja API"
      version: "1.0.0"
    securitySchemes:
      Bearer:
        type: http
        scheme: bearer
        bearerFormat: JWT
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
      security:
        - Bearer: [ ]
  areas:
    path_patterns:
      - ^/api/v1/.*