security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
#        users_in_memory: { memory: null }
        user_provider:
            id: App\Shared\Security\User\UserProvider

    firewalls:
        # Zabezpieczenie trasy logowania (autentykacja JWT)
        login:
            pattern: ^/api/login$
            stateless: true
            security: false
            provider: user_provider
            json_login:
                check_path: /api/login
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # Firewall do zabezpieczania innych tras API
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    # Kontrola dostępu do różnych zasobów w API
    access_control:
        # Otwarty dostęp
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/credit/calculation, roles: PUBLIC_ACCESS }
        # Dostęp tylko z tokenem JWT!
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
