auth_controllers:
    resource:
        path: ../src/Shared/Security/
        namespace: App\Shared\Security
    type: attribute

credit:
    resource:
        path: ../src/Credit/UI/Api/
        namespace: App\Credit\UI\Api
    type: attribute